version: '2'
services:
    personalnotebook-app:
        image: personalnotebook
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://personalnotebook-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=PersonalNotebook
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=personalnotebook-elasticsearch:9300
        ports:
            - 8080:8080
    personalnotebook-mongodb:
        extends:
            file: mongodb.yml
            service: personalnotebook-mongodb
    personalnotebook-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: personalnotebook-elasticsearch
